### default fpga compilation device flags ###
DEFAULT_ALTERA_TARGET     = Cyclone IV E
DEFAULT_ALTERA_DEVICE     = EP4CE22F17C6
DEFAULT_ALTERA_PACKAGE    = normal
DEFAULT_ALTERA_CLOCK_MHZ  = 20
DEFAULT_ALTERA_MIN_TEMP   = 0
DEFAULT_ALTERA_MAX_TEMP   = 85
